### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by geekfrom90s** [UltimateHackers/XSStrike#10]
that is a programming issue as i know 

Traceback (most recent call last):
  File "xsstrike", line 1070, in <module>
    post_choice() #Printing menu items which supports POST method
  File "xsstrike", line 1019, in post_choice
    param_data = extractParams(param_data) #Sending POST data to a module which can arrange them
  File "xsstrike", line 821, in extractParams
    param_data[item.split('=',1)[0]] = item.split('=',1)[1]
IndexError: list index out of range

**Comment by kalinerd** [comment]
same issue when i use post data which is d3v and use Ninja.

**Comment by jane42** [comment]
Cook

**Comment by UltimateHackers** [comment]
XSStrike has been upgraded and the code is totally different.

**Comment by benichmt1** [comment]
I still get this issue in Kali even after the latest changes and dependencies installed:
```
Traceback (most recent call last):
  File "xsstrike", line 756, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 754, in input
    initiator(url, GET, POST)
  File "xsstrike", line 667, in initiator
    WAF_detector(url, '?'+paranames[0]+'='+xsschecker, GET, POST)
IndexError: list index out of range
```

**Comment by UltimateHackers** [comment]
Let me look into this.

**Comment by UltimateHackers** [comment]
@kalinerd @geekfrom90s Can you guys provide me the target you were testing against?
If you have privacy concerns, you can send it privately in mail at s0md3v@gmail.com
Thanks.

**Comment by UltimateHackers** [comment]
Oh I see why you are getting that error, the problem is that you didn't enter any POST data.
If a URL doesn't contain "=" XSStrike assumes that it uses POST method and expects the user to enter POST data.
I will fix it now.

**Comment by UltimateHackers** [comment]
The issue has been fixed.
Now XSStrike will print
```
[-] No parameters to test
```
if you don't submit any parameter.
