### ISSUE TITLE
Error when WAF is active on target

### ISSUE THREAD

**Issue by penetrated** [UltimateHackers/XSStrike#16]
Hey,

There seems to be an error when a WAF is active on a target.

To reproduce the error: 

run python xsstrike

enter the url: https://www.myer.com.au/shop/mystore/StoreLocator?storeSearch=d3v

when "[?] A WAF is active on the target. Would you like to delay requests to evade suspicion? [y/N]"
shows up, press y then enter

it'll output

Traceback (most recent call last):
  File "xsstrike", line 699, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 692, in input
    initiator(url, GET, POST)
  File "xsstrike", line 598, in initiator
    fuzzer(url, param_data) #Launches fuzzer aka Ninja
TypeError: fuzzer() takes exactly 6 arguments (2 given)

![yawns](https://user-images.githubusercontent.com/29808541/35303744-db7db6e6-0047-11e8-92e9-96dbe0ce16c2.png)

**Comment by UltimateHackers** [comment]
Thanks for reporting. I will fix it within an hour.

**Comment by UltimateHackers** [comment]
The issue has been fixed and the fuzzing is working fine but the program still throws an error in later stages so I have to work on error handling.
So I am keeping this issue open to get reminded of it.
Thanks for reporting.

**Comment by UltimateHackers** [comment]
The new update resolves this issue.
Thanks again for reporting.
