### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by UltimateHackers** [UltimateHackers/XSStrike#19]
There's a weird error on [line 718](https://github.com/UltimateHackers/XSStrike/blob/master/xsstrike#L718)
```
[?] Execute project HULK for blind XSS Detection? [Y/n] Traceback (most recent call last):
  File "xsstrike", line 780, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 768, in input
    initiator(url, GET, POST)
  File "xsstrike", line 718, in initiator
    choice = raw_input('%s Execute project HULK for blind XSS Detection? [Y/n] ' % que).lower()
ValueError: I/O operation on closed file
```
I have no idea how to solve this, also the value of payload on line 721 and 722 is different.
Anyone who would like to help? Comment here or start a pull request.
Thanks in advance.

**Comment by kkadosh** [comment]
Hello, I would like to help you for this issue.
Can you give me the steps to reproduce this behavior please?

**Comment by UltimateHackers** [comment]
@kkadosh Can you mail me at s0md3v@gmail.com? Thanks.

**Comment by NovaCygni** [comment]
Will open Pull request tomorrow im going to convert all the code to Python3 for a starter, then expand from there, couple minor things you can tweak and might aswell move to py3 now before it becomes a chore, time to learn some Asyncio ;) :+1:

**Comment by AnanaGame** [comment]
I have the same final error: 
```
File "xsstrike", line 783, in <module>
    input() #This is the true start of the program
  File "xsstrike", line 771, in input
    initiator(url, GET, POST)
  File "xsstrike", line 727, in initiator
    next = raw_input('%s Press enter to execute next payload' % que)
ValueError: I/O operation on closed file
```

**Comment by NovaCygni** [comment]
`_stdin_encoding = sys.stdin.encoding or 'utf-8'

def unicode_input(prompt):
    return raw_input(prompt).decode(_stdin_encoding)`
Something similar might work for you as if I remember right this comes from some form of encoding error...
