### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by mboelen** [UltimateHackers/XSStrike#29]
While reviewing your tool ([XSStrike tool review](https://linuxsecurity.expert/tools/xsstrike/)), we found that your website is not working.

**Comment by UltimateHackers** [comment]
Hi @mboelen ,
I am aware of the issue and will fix it as soon as I am done with my exams.
Thanks for reporting.

**Comment by mboelen** [comment]
You are welcome and good luck with the exams :)

**Comment by UltimateHackers** [comment]
The website is online now.
