### ISSUE TITLE
Feature request!

### ISSUE THREAD

**Issue by its0x08** [UltimateHackers/XSStrike#30]
Hello,
Congrats for the tool. Its nice.
My request is the support for the URI injections whenever there is no GET or POST traditional parameters.
Whenever the site uses Apache mod_rewrite for example:
From
GET http://site.com/index.php?post=test-post
to
GET http://site.com/index/post/test-post/
So the tool can try to inject here 
http://site.com/index/post/test-post/{inject_here}
thanks!

**Comment by UltimateHackers** [comment]
Hi there,
I added this feature in a different branch, you can download that from there.
Thanks for the suggestion.

**Comment by UltimateHackers** [comment]
You are welcome :)
