### ISSUE TITLE
More screenshots

### ISSUE THREAD

**Issue by afzalsayed96** [UltimateHackers/XSStrike#31]
Hi, Love your work! Can you add more screenshots as the current ones are broken?

**Comment by UltimateHackers** [comment]
All 4 screenshots are visible from my browser `Firefox 60.0.1`.
Please try using a different browser.
And if you are trying to say that 4 screenshots are not enough then I don't agree with you because these screenshots show case all the features of XSStrike.

**Comment by afzalsayed96** [comment]
![20180520_190210_rmedited](https://user-images.githubusercontent.com/14029371/40279458-73192700-5c60-11e8-849e-b008ce743bc0.jpg)

Images aren't working on chrome desktop and android.

**Comment by UltimateHackers** [comment]
I just checked it with `Firefox Focus` which is a privacy focused android browser which doesn't store any kind of data at all and everything is perfectly fine.
Also tried after clearing cache of my main browser but everything seems fine from here.
