### ISSUE TITLE
Slow fuzzywuzzy warning

### ISSUE THREAD

**Issue by tbhaxor** [UltimateHackers/XSStrike#34]
When i executed your script i got this message at startup
```
/home/terabyte/.local/lib/python2.7/site-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

PS : its a warning

**Comment by UltimateHackers** [comment]
Errors are **always** self explanatory.
The error in this case clearly indicates that you need to install `python-Levenshtein` module.
That's pretty much it.

**Comment by tbhaxor** [comment]
Then add this `python-Levenshtein` to requirements.txt :smile:
