### ISSUE TITLE
The tool can't be used when the get parameter is not needed？

### ISSUE THREAD

**Issue by kingz40o** [UltimateHackers/XSStrike#36]
The tool can't be used when the get parameter is not needed. for example
`url: http://xxxx/index.php`
`<form method="post" action="/index.php">`
`-----------------------`
`payload: http://xxxx/index.php/"><svg/onload=alert(1)>`
`<form method="post" action="/index.php/"><svg/onload=alert(1)>">`
`-----------------------`

**Comment by UltimateHackers** [comment]
You can add the POST data manually.

**Comment by kingz40o** [comment]
`My payload is submitted via the get method and triggers XSS, like the paylaod submission method above. /index.php/+payload+`

**Comment by kingz40o** [comment]
My payload is submitted via the get method and triggers XSS, like the paylaod submission method above. /index.php/+payload+

**Comment by UltimateHackers** [comment]
For this kind of injection refer to the [custiom injection branch](https://github.com/UltimateHackers/XSStrike/tree/custom-injection) of XSStrike.
You can specify the injection point as follows:
https://example.com/search/*
