### ISSUE TITLE
"Post Param" execution error

### ISSUE THREAD

**Issue by hack0mate** [UltimateHackers/XSStrike#5]
`[?] Enter the target URL: http://*****************.com/*******.php`
`[?] Enter cookie (if any): `
`[!] The URL you entered seems to use POST Method.`
`[?] Enter post data: ******=*******&***=d3v&*****=********&*******=****&****=**&******=******`
1. Striker
2. Ninja
Enter your choice: 1
--------------------------------------------
Traceback (most recent call last):
  File "./xsstrike", line 1115, in <module>
    post_choice() #Printing menu items which supports POST method
  File "./xsstrike", line 1064, in post_choice
    POST()
  File "./xsstrike", line 580, in POST
    param_data = param
NameError: global name 'param' is not defined

**Comment by UltimateHackers** [comment]
[Fixed]
Can you please check it again?
Thanks for reporting.

**Comment by hack0mate** [comment]
Fixed not enough.
Here is an error:[?] Enter the target URL: http://************.**/*********.php
[?] Enter cookie (if any): 
[!] The URL you entered seems to use POST Method.
[?] Enter post data: *********=*******&*****=d3v&******=*****&****=*****&**************=***&*****************=******
1. Striker
2. Ninja
Enter your choice: 1
--------------------------------------------
[>] Payloads loaded: 17
[>] Striking the parameter(s)
[>] Testing parameter: ****
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: ****
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: *********
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: **********
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: ******
>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: 
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
```
Traceback (most recent call last):
  File "xsstrike", line 1121, in <module>
    post_choice() #Printing menu items which supports POST method
  File "xsstrike", line 1064, in post_choice
    POST()
  File "xsstrike", line 651, in POST
    complete(conclusion)
NameError: global name 'conclusion' is not defined
```
