### ISSUE TITLE
Post Param Error

### ISSUE THREAD

**Issue by hack0mate** [UltimateHackers/XSStrike#6]
[?] Enter the target URL: http://************.**/*********.php
[?] Enter cookie (if any): 
[!] The URL you entered seems to use POST Method.
[?] Enter post data: *********=*******&*****=d3v&******=*****&****=*****&**************=***&*****************=******
1. Striker
2. Ninja
Enter your choice: 1
--------------------------------------------
[>] Payloads loaded: 17
[>] Striking the parameter(s)
[>] Testing parameter: ****
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: ****
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: *********
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: **********
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: ******
>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
[>] Testing parameter: 
[>] Payloads injected: 17 / 17
[-] '******' parameter not vulnerable.
```
Traceback (most recent call last):
  File "xsstrike", line 1121, in <module>
    post_choice() #Printing menu items which supports POST method
  File "xsstrike", line 1064, in post_choice
    POST()
  File "xsstrike", line 651, in POST
    complete(conclusion)
NameError: global name 'conclusion' is not defined
```

**Comment by UltimateHackers** [comment]
[Fixed]
Thanks for helping and sorry for writing such a buggy program.
